git config --global alias.full-send '!C:/git-scripts/Windows/full-send.bat'
git config --global alias.send '!C:/git-scripts/Windows/send.bat'
git config --global alias.recv '!C:/git-scripts/Windows/recv.bat'
git config --global alias.ch-br '!C:/git-scripts/Windows/ch-br.bat'
git config --global alias.conf '!C:/git-scripts/Windows/conf.bat'
git config --global alias.br '!C:/git-scripts/Windows/br.bat'
